name: flutter_training
command:
  bootstrap:
    environment:
      flutter: ">=3.16.9 <4.0.0"
      sdk: ">=3.0.0 <4.0.0"
    dependencies:
      cupertino_icons: ^1.0.8
      dio: ^5.7.0
      flutter_modular: ^6.3.4
      firebase_core: ^3.6.0
      firebase_crashlytics: ^4.1.3
      firebase_remote_config: ^5.1.3
      golden_toolkit: ^0.15.0
      intl: ^0.19.0
      rxdart: ^0.28.0
      
    dev_dependencies:
      dart_code_metrics: ^5.7.6
      flutter_lints: ^5.0.0
      mocktail: ^1.0.4

packages:
  - ./**
  - ./**/**